name: Fetch NFL Schedules (scores + closing lines)

on:
  workflow_dispatch: {}   # we'll add cron after it shows up

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "schedules workflow is visible"
