name: Fetch nflfastR from GitHub Raw

on:
  schedule:
    - cron: "0 16 * * *"   # daily 10:00 AM America/Edmonton (16:00 UTC)
  workflow_dispatch: {}

concurrency:
  group: data-refresh
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create target folder
        shell: bash
        run: |
          mkdir -p data/raw/nflverse__nflfastR-play-by-play-data

      - name: Download nflfastR play-by-play by season
        shell: bash
        run: |
          set -e
          BASE="https://raw.githubusercontent.com/nflverse/nflfastR-data/master/data"
          OUT="data/raw/nflverse__nflfastR-play-by-play-data"
          # Adjust end year as new seasons publish
          for Y in $(seq 1999 2025); do
            URL="$BASE/play_by_play_${Y}.csv.gz"
            FILE="$OUT/play_by_play_${Y}.csv.gz"
            echo "Fetching $URL"
            if curl -fsSL -o "$FILE" "$URL"; then
              echo "Saved $FILE"
            else
              echo "Not available for $Y (skipping)"
            fi
          done

      - name: Rebase on latest main
        shell: bash
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Stage files and detect changes
        id: diff
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No local changes after download."
          else
            echo "changed=true"  >> "$GITHUB_OUTPUT"
            echo "Changes detected, will commit."
          fi

      - name: Commit & push updates
        if: steps.diff.outputs.changed == 'true'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: refresh nflverse raw play-by-play"
          git push || (git pull --rebase origin main && git push)
