name: Fetch nflfastR from GitHub Mirror

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

concurrency:
  group: data-refresh
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull nflverse mirror (sparse checkout)
        shell: bash
        run: |
          set -e
          rm -rf tmp_nflverse
          git clone --depth 1 https://github.com/nflverse/nflfastR-data.git tmp_nflverse
          mkdir -p data/raw/nflverse__nflfastR-play-by-play-data
          # Copy season CSVs (adjust patterns if you want parquet)
          rsync -av --include="*/" --include="*play_by_play_*.csv.gz" --exclude="*" \
            tmp_nflverse/data/ \
            data/raw/nflverse__nflfastR-play-by-play-data/
          echo "Mirror copy complete."

      - name: Rebase on latest main
        shell: bash
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Stage files and detect changes
        id: diff
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No local changes after mirror sync."
          else
            echo "changed=true"  >> "$GITHUB_OUTPUT"
            echo "Changes detected, will commit."
          fi

      - name: Commit & push updates
        if: steps.diff.outputs.changed == 'true'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: refresh nflverse github mirror"
          git push || (git pull --rebase origin main && git push)
