name: Fetch nflfastR PBP from Releases

on:
  schedule:
    - cron: "0 16 * * *"   # daily 10:00 AM America/Edmonton (16:00 UTC)
  workflow_dispatch: {}

concurrency:
  group: data-refresh
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create target folder
        shell: bash
        run: mkdir -p data/raw/nflverse__nflfastR-play-by-play-data

      - name: Download PBP CSVs from nflverse releases
        shell: bash
        run: |
          set -e
          OUT="data/raw/nflverse__nflfastR-play-by-play-data"
          base="https://github.com/nflverse/nflverse-data/releases/download/pbp"
          # Adjust end year as new seasons publish
          for Y in $(seq 1999 2025); do
            url="$base/play_by_play_${Y}.csv.gz"
            file="$OUT/play_by_play_${Y}.csv.gz"
            echo "Fetching $url"
            if curl -fL --retry 3 --retry-delay 2 -o "$file.tmp" "$url"; then
              mv "$file.tmp" "$file"
              echo "Saved $file"
            else
              echo "Not available for $Y (skipping)"
              rm -f "$file.tmp"
            fi
          done

      - name: Rebase on latest main
        shell: bash
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Stage files and detect changes
        id: diff
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No local changes after download."
          else
            echo "changed=true"  >> "$GITHUB_OUTPUT"
            echo "Changes detected, will commit."
          fi

      - name: Commit & push updates
        if: steps.diff.outputs.changed == 'true'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: refresh nflverse pbp (releases)"
          git push || (git pull --rebase origin main && git push)
