name: Fetch Kaggle NFL Data

on:
  schedule:
    - cron: "0 16 * * *"   # daily 10:00 AM America/Edmonton (16:00 UTC)
  workflow_dispatch: {}     # allows manual run from Actions tab

concurrency:
  group: data-refresh
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # allow committing data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed for pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Kag
