name: Fetch NFL Results & Closing Lines

on:
  schedule:
    - cron: "15 16 * * *"   # daily, 10:15 AM Edmonton
  workflow_dispatch: {}

concurrency:
  group: fetch-results
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Create targets
        shell: bash
        run: |
          mkdir -p data/external

      - name: Download games + lines from nflverse releases
        shell: bash
        run: |
          set -e
          BASE="https://github.com/nflverse/nflverse-data/releases/download"
          # game outcomes (one file per season)
          for Y in $(seq 1999 2025); do
            curl -fL --retry 3 -o data/external/games_${Y}.csv.gz "$BASE/games/games_${Y}.csv.gz" || true
            curl -fL --retry 3 -o data/external/lines_${Y}.csv.gz "$BASE/lines/lines_${Y}.csv.gz" || true
          done

      - name: Rebase & commit if changed
        shell: bash
        run: |
          git fetch origin main
          git pull --rebase origin main || true
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: refresh games & lines"
            git push || (git pull --rebase origin main && git push)
          fi